name: Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run:  sudo apt-get install mingw-w64
    - name: make
      run:  cd OpenGL && \
            make release
