name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run:  sudo apt-get install git make lib-glut
    - name: make
      run:  cd OpenGL &&
            make build