name: Compiles ?

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run:  sudo apt-get install git make freeglut3 freeglut3-dev libglew1.5 libglew1.5-dev libglu1-mesa libglu1-mesa-dev libgl1-mesa-glx libgl1-mesa-dev &&
            sudo mkdir -p /usr/local/share/MinGW/freeglut/include/  &&
            
    - name: make
      run:  cd OpenGL &&
            make build